#!/usr/bin/env bash

# Install Nginx
sudo apt-get update -y && \
sudo apt-get install -y nginx

if [ $? -eq 0 ]; then
    # Configure Nginx
    echo -e \
    "http {
        root /var/www/school;
        index index.html;
        server {
            listen 80;
            location / {
            }
        }
    }
    events {
    }" > /etc/nginx/nginx.conf

    # Create the directory and "Hello World!" index.html
    mkdir -p /var/www/school
    echo "Hello World!" > /var/www/school/index.html

    # Start Nginx
    service nginx start

    if [ $? -ne 0 ]; then
        echo "Problem starting nginx"
        exit 1
    fi
else
    echo "Could not install nginx"
    exit 1
fi

exit 0
