#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

# Update package lists
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Create a custom index page
echo "School" > /var/www/html/index.nginx-debian.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Configure Nginx
# Add a redirect rule and custom 404 error page
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }

    error_page 404 /custom_404.html;

    location /redirect_me {
        return 301 https://google.com/search;
    }

    add_header X-Served-By \$HOSTNAME;
}
EOF

# Reload Nginx configuration
nginx -s reload
